[book]
authors = ["Yannick Seurin"]
language = "en"
multilingual = false
src = "src"
title = "Crypto Book (Work in Progress)"

[output.html]
site-url = "/crypto-book/"
no-section-label = false
additional-css = ["./assets/custom.css"]
additional-js = ["./assets/mermaid.min.js", "./assets/mermaid-init.js"]
git-repository-url = "https://github.com/yannickseurin/crypto-book"
default-theme = "rust"
preferred-dark-theme = "ayu"

[output.html.fold]
enable = true
level = 0

[output.html.playground]
runnable = false

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[preprocessor.mathpunc]
command = "mdbook-mathpunc"
before = ["katex"]

[preprocessor.katex]
after = ["links"]
macros = "src/macros.txt"
block-delimiter = {left = "\\[", right = "\\]"}
trust = true

[preprocessor.mermaid]
command = "mdbook-mermaid"
