[book]
authors = ["Yannick Seurin"]
language = "en"
multilingual = false
src = "src"
title = "Crypto Book (Work in Progress)"

[output.html]
site-url = "/crypto-book/"
no-section-label = false
additional-css = ["./assets/custom.css", "theme/pagetoc.css", "./assets/mdbook-admonish.css", "./assets/mdbook-admonish-custom.css"]
additional-js = ["./assets/mermaid.min.js", "./assets/mermaid-init.js", "theme/pagetoc.js"]
git-repository-url = "https://github.com/yannickseurin/crypto-book"
default-theme = "light"
preferred-dark-theme = "ayu"

[output.html.fold]
enable = true
level = 0

[output.html.playground]
runnable = false

[preprocessor.mathpunc]
before = ["katex"]

[preprocessor.katex]
after = ["links"]
macros = "src/macros.txt"
block-delimiter = {left = "\\[", right = "\\]"}
trust = true

[preprocessor.toc]
renderer = ["html"]

[preprocessor.mermaid]

[preprocessor.numthm]
prefix = true

[preprocessor.numeq]
prefix = true

[preprocessor.footnote]
after = ["numthm"]

[preprocessor.admonish]
command = "mdbook-admonish"
assets_version = "3.0.2" # do not edit: managed by `mdbook-admonish install`

[[preprocessor.admonish.custom]]
directive = "proof"
icon = "./assets/scroll.svg"
color = "#ffd700"

[[preprocessor.admonish.custom]]
directive = "jump"
icon = "./assets/jump.svg"
color = "#66cdaa"
title = "Jumping ahead"
