name: publish

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install mdbook and preprocessors
        run: cargo install mdbook mdbook-katex mdbook-toc mdbook-footnote mdbook-mermaid mdbook-mathpunc mdbook-numeq mdbook-numthm mdbook-admonish

      - name: Generate css for mdbook-admonish
        run: |
          mdbook-admonish install --css-dir ./assets
          mdbook-admonish generate-custom ./assets/mdbook-admonish-custom.css

      - name: Build html
        run: mdbook build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
